# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'univents' do

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
pod 'GoogleMaps'
pod 'Fabric'
pod 'Crashlytics'
pod 'Firebase/Core', '~> 5.10'
pod 'Firebase/Messaging', '~> 5.10'





end
