export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const SAVE_USER = "SAVE_USER";
export const UPDATE_LOGIN_INFO = "UPDATE_LOGIN_INFO";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const START_LOGIN = "START_LOGIN";
export const CLEAR_USER = "CLEAR_USER";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const UPDATE_EVENT_INFO = "UPDATE_EVENT_INFO";
export const CLEAR_EVENT_INFO = "CLEAR_EVENT_INFO";

export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_START = "FETCH_START";

export const FETCH_USER_EVENTS = "FETCH_USER_EVENTS";
export const STORE_LOCAL_EVENT = "STORE_LOCAL_EVENT";

export const START_PUBLISH = "START_PUBLISH";
export const PUBLISH_SUCCESS = "PUBLISH_SUCCESS";
export const PUBLISH_FAIL = "PUBLISH_FAIL";
